# File for Pull Request on master branch
name: PR on master

# When a PR is opened to master
on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  build:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest nodes only
        node-version: [14.x]
        # Define Steps
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Make sure we have all branches
      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin master

        # https://github.com/marketplace/actions/npm-install-cache
      - uses: c-hive/gha-npm-cache@v1
        if: ${{ !env.ACT }}

      - uses: nrwl/nx-set-shas@v2

      - name: Install environment
        run: npm ci --include=dev

      - run: npm run lint
      - run: npm run test
      - run: npx run build
